faet: git actions

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,1 +1,169 @@
+name: Deploy
 
+on:
+  push:
+    branches:
+      - master
+      - main
+  pull_request:
+    branches:
+      - master
+      - main
+    types: [opened, synchronize, reopened]
+  release:
+    types: [created]
+
+jobs:
+  build:
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Set up Java 21
+        uses: actions/setup-java@v2
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+
+      - name: Build Project with Maven
+        run: |
+          echo "Construindo o projeto..."
+          mvn clean install
+
+  test:
+    runs-on: ubuntu-22.04
+    needs: build
+    services:
+      rabbitmq:
+        image: "rabbitmq:management"
+        ports:
+          - 5672:5672
+          - 15672:15672
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Set up Java 21
+        uses: actions/setup-java@v2
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+
+      - name: Esperar o RabbitMQ iniciar
+        run: |
+          for i in {1..30}; do
+            nc -z localhost 5672 && echo "RabbitMQ está rodando!" && exit 0
+            echo "Aguardando RabbitMQ..."
+            sleep 2
+          done
+          echo "RabbitMQ não iniciou!" && exit 1
+
+      - name: Run Tests
+        run: |
+          mvn test
+
+      - name: Upload coverage report
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage
+          path: target/site/jacoco/jacoco.xml
+
+  sonar:
+    runs-on: ubuntu-latest
+    needs: test
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Set up Java 21
+        uses: actions/setup-java@v2
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+
+      - name: Cache SonarQube packages
+        uses: actions/cache@v4
+        with:
+          path: ~/.sonar/cache
+          key: ${{ runner.os }}-sonar
+          restore-keys: ${{ runner.os }}-sonar
+
+      - name: Cache Maven packages
+        uses: actions/cache@v4
+        with:
+          path: ~/.m2
+          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+          restore-keys: ${{ runner.os }}-m2
+
+      - name: Build and analyze with SonarQube
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_ORG: miltonrubro
+        run: |
+          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
+            -Dsonar.projectKey=MILTONRUBRO/api-ms-orders \
+            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
+            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
+
+  check_coverage:
+    runs-on: ubuntu-latest
+    needs: sonar
+    if: github.event_name == 'pull_request'
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: SonarQube Quality Gate Check
+        run: |
+          sonar_status=$(curl -s -u ${{ secrets.SONAR_TOKEN }} "https://sonarcloud.io/api/qualitygates/project_status?projectKey=MILTONRUBRO/api-ms-orders")
+          
+          quality_gate_status=$(echo $sonar_status | jq -r '.projectStatus.status')
+          
+          if [ "$quality_gate_status" != "OK" ]; then
+            echo "SonarQube Quality Gate failed: Coverage is below 70%" && exit 1
+          else
+            echo "SonarQube Quality Gate passed!"
+
+  deploy_pre:
+    runs-on: ubuntu-22.04
+    needs: sonar
+    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Configurar variáveis no Heroku
+        run: |
+          heroku config:set RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }} --app api-ms-orders
+        env:
+          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
+
+      - uses: akhileshns/heroku-deploy@v3.13.15
+        with:
+          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
+          heroku_app_name: "api-ms-orders"
+          heroku_email: "milton-rubro@hotmail.com"
+
+  deploy_prod:
+    runs-on: ubuntu-22.04
+    needs: sonar
+    if: github.event_name == 'release' && github.event.action == 'created'
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Configurar variáveis no Heroku
+        run: |
+          heroku config:set RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }} --app api-ms-orders
+        env:
+          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
+
+      - uses: akhileshns/heroku-deploy@v3.13.15
+        with:
+          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
+          heroku_app_name: "api-ms-orders"
+          heroku_email: "milton-rubro@hotmail.com
+"
